apiVersion: v1
entries:
  descheduler:
  - apiVersion: v1
    appVersion: v0.5.0-4-ga7ceb671
    created: 2018-05-09T07:38:53.703384538-07:00
    description: A Helm chart for Kubernetes Descheduler
    digest: df89087cd7d16c413c29ef0b1ea6cf5e1844caae1844812a7069e2da6a60f80b
    name: descheduler
    urls:
    - descheduler-0.1.0.tgz
    version: 0.1.0
  efk:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-05-09T07:38:53.704977996-07:00
    description: A Helm chart for EFK stack
    digest: 12573fe5a113689145e34c0dcf8c73bcd6286d82fe16738d3787dd0b300047be
    name: efk
    urls:
    - efk-0.1.0.tgz
    version: 0.1.0
  elasticsearch:
  - apiVersion: v1
    appVersion: 6.1.3
    created: 2018-05-09T07:38:53.70623027-07:00
    description: A Helm chart for Elasticsearch cluster
    digest: d117aa89f27ef7adad3a4ee75620e0eb6e1cd251682bd6fa71d7ff022125e9b6
    maintainers:
    - email: frankmariette@carfax.com
      name: frankmariette
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 6.1.3
    created: 2018-05-09T07:38:53.70524296-07:00
    description: A Helm chart for Elasticsearch cluster
    digest: 32a25b05c73cc92b49fc53b64d25cee44d28e1062db1ef12f2cbcb0e260d0019
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.3.tgz
    version: 0.1.3
  elasticsearch-operator:
  - apiVersion: v1
    appVersion: 0.0.12
    created: 2018-05-09T07:38:53.707545039-07:00
    description: A Helm chart for Elasticsearch operator
    digest: 7d1aff1a6e4903b58ba24496cf464bf2cc4bebd494c88a2229aff596a5591977
    maintainers:
    - email: frankmariette@carfax.com
      name: frankmariette
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: 0.0.12
    created: 2018-05-09T07:38:53.706860363-07:00
    description: A Helm chart for Elasticsearch operator
    digest: f909a7a19ec3e04259a40728c7428515701aed1f8cae7407c8b6a993b6e083d8
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 0.0.10
    created: 2018-05-09T07:38:53.706559019-07:00
    description: A Helm chart for Elasticsearch operator
    digest: dea5f18a301f11dee2aef9ac1dd3b44069e4bc128c8c32f8e1322a55a385a282
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.3.tgz
    version: 0.1.3
  kibana:
  - appVersion: 6.1.3
    created: 2018-05-09T07:38:53.70832767-07:00
    description: Kibana is an open source data visualization plugin for Elasticsearch
    digest: 6257a3e659a8e70ab0cde88fd0e60c53b30900afe6ffaff0c6775b61ab19d31f
    engine: gotpl
    home: https://www.elastic.co/products/kibana
    icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
    keywords:
    - elasticsearch
    - kibana
    maintainers:
    - email: mikegroner@carfax.com
      name: Mike Groner
    - email: frankmariette@carfax.com
      name: frankmariette
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - kibana-0.4.2.tgz
    version: 0.4.2
generated: 2018-05-09T07:38:53.702138455-07:00
